/* decks.js
   Shared decks for all games.

   Format:
   DECKS = {
     DECK_NAME: [{ de: "term", en: "definition" }, ...]
   }
*/

const DECKS = {
  BIOL112_EVOLUTION: [
    { de: "Evolution", en: "Change in heritable traits of populations over generations." },
    { de: "Descent with modification", en: "Inheritance of traits from ancestors with changes over time." },
    { de: "Population vs individual", en: "Individuals do not evolve; populations do." },
    { de: "Heritable trait", en: "A trait that can be passed from parents to offspring." },
    { de: "Acquired trait", en: "A trait gained during life that is not inherited." },
    { de: "Allele", en: "Different versions of the same gene." },
    { de: "Variation", en: "Differences in traits among individuals in a population." },
    { de: "Natural selection", en: "Differential survival and reproduction based on heritable traits." },
    { de: "Fitness", en: "An organism’s ability to survive and reproduce." },
    { de: "Reproductive success", en: "Number of viable offspring produced." },
    { de: "Differential reproduction", en: "Individuals with certain traits reproduce more than others." },
    { de: "Directional selection", en: "Selection favoring one extreme trait value." },
    { de: "Stabilizing selection", en: "Selection favoring intermediate trait values." },
    { de: "Disruptive selection", en: "Selection favoring extreme trait values over intermediates." },
    { de: "Artificial selection", en: "Human-directed breeding for specific traits." },
    { de: "Transitional fossil", en: "A fossil showing traits intermediate between groups." },
    { de: "Tree of life", en: "A representation of evolutionary relationships among all organisms." },

    { de: "Gene flow", en: "Movement of alleles between populations." },
    { de: "Genetic drift", en: "Random changes in allele frequencies, strongest in small populations." },
    { de: "Allele frequency", en: "Proportion of a specific allele in a population." },
    { de: "Bottleneck effect", en: "Loss of genetic diversity due to a sharp population reduction." },
    { de: "Founder effect", en: "Genetic drift occurring when a small group starts a new population." },
    { de: "Migration", en: "Movement of individuals between populations." },
    { de: "Gamete dispersal", en: "Movement of reproductive cells between populations." },
    { de: "Horizontal gene transfer", en: "Transfer of genes between organisms outside reproduction." },
    { de: "Random sampling", en: "Chance effects influencing which alleles are passed on." },
    { de: "Fixation", en: "When an allele reaches 100% frequency in a population." },
    { de: "Loss of alleles", en: "Complete disappearance of an allele from a population." },
    { de: "Population size", en: "Number of individuals in a population affecting evolutionary processes." },
    { de: "Non-adaptive evolution", en: "Evolutionary change not driven by natural selection." },
    { de: "Null model", en: "A baseline model assuming no evolutionary forces are acting." },
    { de: "Hardy–Weinberg equilibrium", en: "Condition where allele frequencies remain constant over time." },
    { de: "Population structure", en: "Genetic differences among populations of the same species." },

    { de: "Mutation", en: "A change in DNA sequence." },
    { de: "Genetic variation", en: "Differences in DNA among individuals." },
    { de: "Point mutation", en: "A change in a single nucleotide." },
    { de: "Insertion", en: "Addition of one or more nucleotides." },
    { de: "Deletion", en: "Removal of one or more nucleotides." },
    { de: "Gene duplication", en: "Creation of an extra copy of a gene." },
    { de: "Whole genome duplication", en: "Duplication of an entire genome." },
    { de: "Regulatory mutation", en: "Mutation affecting gene expression rather than protein structure." },
    { de: "Beneficial mutation", en: "Mutation that increases fitness." },
    { de: "Neutral mutation", en: "Mutation with no effect on fitness." },
    { de: "Deleterious mutation", en: "Mutation that decreases fitness." },
    { de: "Trade-offs", en: "Situations where improvement in one trait reduces another." },
    { de: "Gene expression", en: "Process by which genes produce functional products." },
    { de: "Mutation accumulation", en: "Build-up of mutations over time." },
    { de: "Selective environment", en: "Environmental conditions influencing selection." },

    { de: "Macroevolution", en: "Evolutionary change above the species level." },
    { de: "Microevolution", en: "Changes in allele frequencies within populations." },
    { de: "Deep time", en: "Vast geological time over which evolution occurs." },
    { de: "Speciation", en: "Formation of new species." },
    { de: "Diversification", en: "Increase in species number within a lineage." },
    { de: "Extinction", en: "Permanent loss of a species." },
    { de: "Phylogeny", en: "Evolutionary history of a group." },
    { de: "Phylogenetic tree", en: "Diagram showing evolutionary relationships." },
    { de: "Node", en: "Point representing a common ancestor." },
    { de: "Branch", en: "Line representing evolutionary lineage." },
    { de: "Taxon / taxa", en: "A named group of organisms." },
    { de: "Sister taxa", en: "Two lineages sharing an immediate common ancestor." },
    { de: "Clade", en: "A group consisting of an ancestor and all descendants." },
    { de: "Monophyletic", en: "Group containing an ancestor and all descendants." },
    { de: "Paraphyletic", en: "Group containing an ancestor but not all descendants." },
    { de: "Polyphyletic", en: "Group lacking a common ancestor." },
    { de: "Homology", en: "Similarity due to shared ancestry." },
    { de: "Convergent evolution", en: "Independent evolution of similar traits." },
    { de: "Ancestral trait", en: "Trait present in a common ancestor." },
    { de: "Derived trait", en: "Trait that evolved from an ancestral condition." },
    { de: "Adaptive radiation", en: "Rapid diversification into multiple niches." },
    { de: "Gradualism", en: "Slow, continuous evolutionary change." },
    { de: "Punctuated equilibrium", en: "Long periods of stasis interrupted by rapid change." },

    { de: "Species", en: "A group of organisms that form independent lineages." },
    { de: "Biological Species Concept", en: "Species defined by reproductive isolation." },
    { de: "Reproductive isolation", en: "Barriers preventing gene flow between populations." },
    { de: "Morphological Species Concept", en: "Species defined by physical characteristics." },
    { de: "Phylogenetic Species Concept", en: "Species defined by evolutionary history." },
    { de: "Cryptic species", en: "Distinct species that look very similar." },
    { de: "Asexual organisms", en: "Organisms reproducing without mating." },
    { de: "Fossils", en: "Preserved remains or traces of past life." },
    { de: "Operational Taxonomic Units (OTUs)", en: "Units used to classify organisms in analyses." },
    { de: "Independently evolving lineages", en: "Groups evolving separately over time." },

    { de: "Prezygotic barrier", en: "Barrier preventing fertilization." },
    { de: "Habitat isolation", en: "Species live in different environments." },
    { de: "Temporal isolation", en: "Species reproduce at different times." },
    { de: "Behavioral isolation", en: "Differences in mating behaviors." },
    { de: "Mechanical isolation", en: "Incompatible reproductive structures." },
    { de: "Assortative mating", en: "Preference for mating with similar individuals." },
    { de: "Courtship behavior", en: "Actions used to attract mates." },
    { de: "Gene flow interruption", en: "Prevention of allele exchange." },

    { de: "Postzygotic barrier", en: "Barrier occurring after fertilization." },
    { de: "Hybrid inviability", en: "Hybrid fails to develop properly." },
    { de: "Hybrid sterility", en: "Hybrid cannot reproduce." },
    { de: "Hybrid breakdown", en: "Later-generation hybrids have reduced fitness." },
    { de: "Genetic incompatibility", en: "Genes do not function well together." },
    { de: "Reduced fitness", en: "Lower survival or reproduction." },
    { de: "Chromosomal mismatch", en: "Incompatible chromosome structures." },

    { de: "Allopatric speciation", en: "Speciation due to geographic isolation." },
    { de: "Peripatric speciation", en: "Speciation in small, isolated populations." },
    { de: "Parapatric speciation", en: "Speciation across a continuous range." },
    { de: "Sympatric speciation", en: "Speciation without geographic separation." },
    { de: "Geographic isolation", en: "Physical separation of populations." },
    { de: "Founder population", en: "Small group starting a new population." },
    { de: "Divergent selection", en: "Selection favoring different traits in different environments." },
    { de: "Selection vs gene flow", en: "Balance between local adaptation and allele movement." },
    { de: "Polyploidy", en: "Possession of more than two chromosome sets." },
    { de: "Host switching", en: "Shift to a new host species." },
    { de: "Ecological specialization", en: "Adaptation to a specific niche." }
  ]
};
